alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
databases:
  - cluster_name: db-mysql-blr
    db_name: brad-laravel
    db_user: doadmin
    engine: MYSQL
    name: db-mysql-blr
    production: true
    version: "8"
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: bradtraversy-laravel-sample
      match:
        path:
          prefix: /
name: laravel-session-test
region: fra
services:
  - environment_slug: php
    envs:
      - key: APP_NAME
        scope: RUN_AND_BUILD_TIME
        value: Laravel
      - key: APP_ENV
        scope: RUN_AND_BUILD_TIME
        value: local
      - key: APP_KEY
        scope: RUN_AND_BUILD_TIME
        value: base64:iHBAbOeqjOFlnYhGIhzlOK/Z9X/3HYJw4ALqRLsoKgg=
      - key: APP_DEBUG
        scope: RUN_AND_BUILD_TIME
        value: "true"
      - key: APP_URL
        scope: RUN_AND_BUILD_TIME
        value: http://localhost
      - key: LOG_CHANNEL
        scope: RUN_AND_BUILD_TIME
        value: stack
      - key: LOG_DEPRECATIONS_CHANNEL
        scope: RUN_AND_BUILD_TIME
        value: "null"
      - key: LOG_LEVEL
        scope: RUN_AND_BUILD_TIME
        value: debug
      - key: DB_CONNECTION
        scope: RUN_AND_BUILD_TIME
        value: mysql
      - key: DB_HOST
        scope: RUN_AND_BUILD_TIME
        value: db-mysql-blr-do-user-11648032-0.b.db.ondigitalocean.com
      - key: DB_PORT
        scope: RUN_AND_BUILD_TIME
        value: "25060"
      - key: DB_DATABASE
        scope: RUN_AND_BUILD_TIME
        value: brad-laravel
      - key: DB_USERNAME
        scope: RUN_AND_BUILD_TIME
        value: doadmin
      - key: DB_PASSWORD
        scope: RUN_AND_BUILD_TIME
        value: AVNS_XdYhFf9oNHYUtNoZbAV
      - key: BROADCAST_DRIVER
        scope: RUN_AND_BUILD_TIME
        value: log
      - key: CACHE_DRIVER
        scope: RUN_AND_BUILD_TIME
        value: file
      - key: FILESYSTEM_DISK
        scope: RUN_AND_BUILD_TIME
        value: local
      - key: QUEUE_CONNECTION
        scope: RUN_AND_BUILD_TIME
        value: sync
      - key: SESSION_DRIVER
        scope: RUN_AND_BUILD_TIME
        value: database
      - key: SESSION_LIFETIME
        scope: RUN_AND_BUILD_TIME
        value: "120"
      - key: MEMCACHED_HOST
        scope: RUN_AND_BUILD_TIME
        value: 127.0.0.1
      - key: REDIS_HOST
        scope: RUN_AND_BUILD_TIME
        value: 127.0.0.1
      - key: REDIS_PASSWORD
        scope: RUN_AND_BUILD_TIME
        value: "null"
      - key: REDIS_PORT
        scope: RUN_AND_BUILD_TIME
        value: "6379"
      - key: MAIL_MAILER
        scope: RUN_AND_BUILD_TIME
        value: smtp
      - key: MAIL_HOST
        scope: RUN_AND_BUILD_TIME
        value: mailhog
      - key: MAIL_PORT
        scope: RUN_AND_BUILD_TIME
        value: "1025"
      - key: MAIL_USERNAME
        scope: RUN_AND_BUILD_TIME
        value: "null"
      - key: MAIL_PASSWORD
        scope: RUN_AND_BUILD_TIME
        value: "null"
      - key: MAIL_ENCRYPTION
        scope: RUN_AND_BUILD_TIME
        value: "null"
      - key: MAIL_FROM_ADDRESS
        scope: RUN_AND_BUILD_TIME
        value: hello@example.com
      - key: MAIL_FROM_NAME
        scope: RUN_AND_BUILD_TIME
        value: ${APP_NAME}
      - key: AWS_ACCESS_KEY_ID
        scope: RUN_AND_BUILD_TIME
      - key: AWS_SECRET_ACCESS_KEY
        scope: RUN_AND_BUILD_TIME
      - key: AWS_DEFAULT_REGION
        scope: RUN_AND_BUILD_TIME
        value: us-east-1
      - key: AWS_BUCKET
        scope: RUN_AND_BUILD_TIME
      - key: AWS_USE_PATH_STYLE_ENDPOINT
        scope: RUN_AND_BUILD_TIME
        value: "false"
      - key: PUSHER_APP_ID
        scope: RUN_AND_BUILD_TIME
      - key: PUSHER_APP_KEY
        scope: RUN_AND_BUILD_TIME
      - key: PUSHER_APP_SECRET
        scope: RUN_AND_BUILD_TIME
      - key: PUSHER_APP_CLUSTER
        scope: RUN_AND_BUILD_TIME
        value: mt1
      - key: MIX_PUSHER_APP_KEY
        scope: RUN_AND_BUILD_TIME
        value: sample
      - key: MIX_PUSHER_APP_CLUSTER
        scope: RUN_AND_BUILD_TIME
        value: sample
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db-mysql-blr.DATABASE_URL}
    github:
      branch: b-01-database-driver
      deploy_on_push: true
      repo: techswarn/bradtraversy-laravel-sample
    http_port: 8000
    instance_count: 2
    instance_size_slug: professional-xs
    name: bradtraversy-laravel-sample
    run_command: heroku-php-apache2 -F php-fpm.conf public/
    source_dir: /
